LLAMA_MODEL = "ollama/llama3.2:latest"
LLAMA_BASE_URL = "http://localhost:11434"

GEMINI_MODEL = "gemini/gemini-1.5-flash"
GEMINI_API_KEY = "AIzaSyB1CtoL6UPjbvd6f27rirT64UkfPQHhYJY"

EXCEL_PATH = "lead_data.xlsx"
